// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCopdcdRiwCPMsTAMtObvLs2BOt3CyBSjs',
    appId: '1:809542258805:web:2d4648be5816c21ad8e83c',
    messagingSenderId: '809542258805',
    projectId: 'event-management-875ec',
    authDomain: 'event-management-875ec.firebaseapp.com',
    storageBucket: 'event-management-875ec.appspot.com',
    measurementId: 'G-K32W8E07CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByshqgTP5Wf_q-80JymEtszk7BwaAl5SI',
    appId: '1:809542258805:android:7414fdf520f534aad8e83c',
    messagingSenderId: '809542258805',
    projectId: 'event-management-875ec',
    storageBucket: 'event-management-875ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFvfjOnyh7IfPLS51JG8RRyazFuppXO3o',
    appId: '1:809542258805:ios:de18832308073d9dd8e83c',
    messagingSenderId: '809542258805',
    projectId: 'event-management-875ec',
    storageBucket: 'event-management-875ec.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFvfjOnyh7IfPLS51JG8RRyazFuppXO3o',
    appId: '1:809542258805:ios:de18832308073d9dd8e83c',
    messagingSenderId: '809542258805',
    projectId: 'event-management-875ec',
    storageBucket: 'event-management-875ec.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCopdcdRiwCPMsTAMtObvLs2BOt3CyBSjs',
    appId: '1:809542258805:web:a4548dd83af7aa77d8e83c',
    messagingSenderId: '809542258805',
    projectId: 'event-management-875ec',
    authDomain: 'event-management-875ec.firebaseapp.com',
    storageBucket: 'event-management-875ec.appspot.com',
    measurementId: 'G-VZ5G4V3BS5',
  );
}
